[global]
error_log = /var/log/contentify/php/fpm-error.log

[www]
catch_workers_output = yes
access.log = /var/log/contentify/php/fpm-access.log
access.format = "%R - %u %t \"%m %r\" %s %f %d"
clear_env = no
