<?php

namespace Contentify;

use DOMDocument;
use DOMElement;
use DOMNode;

/**
 * Restricts HTML generated by the legacy BBCode parser to its intended output.
 *
 * The parser escapes normal text, but historically copied tag properties into
 * href, src, style and class attributes without escaping them first.
 */
final class HtmlSanitizer
{
    private const ALLOWED_ELEMENTS = [
        'a', 'blockquote', 'br', 'code', 'del', 'div', 'em', 'iframe', 'img',
        'li', 'ol', 'pre', 'span', 'strong', 'ul',
    ];

    public static function sanitizeBbCode(string $html): string
    {
        if ($html === '') {
            return '';
        }

        $document = new DOMDocument('1.0', 'UTF-8');
        $previous = libxml_use_internal_errors(true);
        $loaded = $document->loadHTML(
            '<?xml encoding="UTF-8"><div id="contentify-bbcode-root">'.$html.'</div>',
            LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD
        );
        libxml_clear_errors();
        libxml_use_internal_errors($previous);

        if (! $loaded) {
            return htmlspecialchars(strip_tags($html), ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
        }

        $root = $document->getElementById('contentify-bbcode-root');
        if (! $root) {
            return '';
        }

        self::sanitizeChildren($root);

        $safe = '';
        foreach ($root->childNodes as $child) {
            $safe .= $document->saveHTML($child);
        }

        return $safe;
    }

    private static function sanitizeChildren(DOMNode $parent): void
    {
        for ($node = $parent->firstChild; $node !== null;) {
            $next = $node->nextSibling;

            if ($node instanceof DOMElement) {
                $tag = strtolower($node->tagName);
                if (! in_array($tag, self::ALLOWED_ELEMENTS, true)) {
                    self::removeElement($node);
                    $node = $next;
                    continue;
                }

                self::sanitizeElement($node, $tag);
                self::sanitizeChildren($node);
            }

            $node = $next;
        }
    }

    private static function sanitizeElement(DOMElement $element, string $tag): void
    {
        $attributes = [];
        foreach ($element->attributes as $attribute) {
            $attributes[$attribute->name] = $attribute->value;
        }
        foreach (array_keys($attributes) as $attribute) {
            $element->removeAttribute($attribute);
        }

        if ($tag === 'a') {
            $href = self::safeUri($attributes['href'] ?? '', true);
            if ($href !== null) {
                $element->setAttribute('href', $href);
                $element->setAttribute('rel', 'nofollow noopener noreferrer');
            }
        }

        if ($tag === 'img') {
            $src = self::safeUri($attributes['src'] ?? '', false);
            if ($src !== null) {
                $element->setAttribute('src', $src);
                $element->setAttribute('alt', '');
                $element->setAttribute('loading', 'lazy');
            } else {
                self::removeElement($element);
            }
        }

        if ($tag === 'iframe') {
            $src = $attributes['src'] ?? '';
            if (! preg_match('~^https://www\.youtube\.com/embed/[A-Za-z0-9_-]{6,20}$~D', $src)) {
                self::removeElement($element);
                return;
            }
            $element->setAttribute('class', 'youtube-player');
            $element->setAttribute('src', $src);
            $element->setAttribute('sandbox', 'allow-scripts allow-same-origin allow-presentation');
            $element->setAttribute('allowfullscreen', 'allowfullscreen');
        }

        $style = self::safeStyle($tag, $attributes['style'] ?? '');
        if ($style !== null) {
            $element->setAttribute('style', $style);
        }

        if ($tag === 'span' && ($attributes['class'] ?? '') === 'author') {
            $element->setAttribute('class', 'author');
        } elseif ($tag === 'div' && ($attributes['class'] ?? '') === 'spoiler') {
            $element->setAttribute('class', 'spoiler');
        }
    }

    private static function safeUri(string $uri, bool $allowMail): ?string
    {
        $uri = trim(html_entity_decode($uri, ENT_QUOTES | ENT_HTML5, 'UTF-8'));
        if ($uri === '' || preg_match('/[\x00-\x20\x7F]/', $uri)) {
            return null;
        }
        if (str_starts_with($uri, '/') && ! str_starts_with($uri, '//')) {
            return $uri;
        }
        if (str_starts_with($uri, '#')) {
            return $uri;
        }

        $scheme = strtolower((string) parse_url($uri, PHP_URL_SCHEME));
        $allowed = $allowMail ? ['http', 'https', 'mailto'] : ['http', 'https'];

        return in_array($scheme, $allowed, true) ? $uri : null;
    }

    private static function safeStyle(string $tag, string $style): ?string
    {
        $style = trim($style);
        if ($tag === 'span' && $style === 'text-decoration: underline') {
            return $style;
        }
        if ($tag === 'span' && preg_match('/^font-size: (?:[1-9][0-9]?|100|1[0-9]{2}|200)%$/D', $style)) {
            return $style;
        }
        if ($tag === 'span' && preg_match('/^color: (?:#[0-9a-fA-F]{3,8}|[A-Za-z]{1,20})$/D', $style)) {
            return $style;
        }
        if ($tag === 'span' && preg_match('/^font-family: [A-Za-z0-9 ,\'"_-]{1,100}$/D', $style)) {
            return $style;
        }
        if ($tag === 'ol' && in_array($style, [
            'list-style-type: lower-roman',
            'list-style-type: lower-alpha',
        ], true)) {
            return $style;
        }
        if ($tag === 'div' && in_array($style, [
            'text-align: left',
            'text-align: center',
            'text-align: right',
        ], true)) {
            return $style;
        }

        return null;
    }

    private static function removeElement(DOMElement $element): void
    {
        $element->parentNode?->removeChild($element);
    }
}
